---
title: "Background"
author: "Bob Verity"
date: "Last updated: `r format(Sys.Date(), '%d %b %Y')`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Background}
  %\VignetteEngine{knitr::knitr}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## 1. What are *pfhrp2* deletions?

The majority of malaria diagnosis worldwide relies on rapid diagnostic tests (RDTs). A large proportion of these tests work by detecting the presence of the HPR2 protein in the blood of an infected individual, which reacts to give a positive result. However, *Plasmodium* parasites have been found that carry a deletion of the *pfhrp2* gene. Without the *pfhrp2* gene these parasites do not express the HPR2 protein, rendering them invisible to testing by HRP2-based RDTs. This can present a major clinical problem if these gene deletions are at high prevalence in the population as patients presenting with signs of malaria may be misdiagnosed resulting in treatment delays or missed cases.

## 2. Assumptions of DRpower

We assume that our aim is to design a survey to estimate the prevalence of *pfhrp2/3* deletions within a given region. More specifically, our aim is to determine whether the prevalence of deletions is above a given threshold (5% by default, although this can be changed).

We assume that this is a "province" level study. The exact meaning of this term will vary in geographical size from one province to the next, but what really matters here is that we are aiming to form conclusions about the prevalence of *pfhrp2/3* deletions at a level that is higher than just the sites used in the study. In other words, there is some degree of extrapolation from our handful of sites to a wider geographic area.

We will refer to the sites at which people are tested as "clusters", which in reality are usually health facilities. The methods in DRpower can be used for a single cluster design, but **we strongly advise against this** if the objective is to estimate the prevalence of deletions at the province level. The reason for advocating against a single cluster design is that a single cluster may vary significantly from the province-level average, for example due to spatial heterogeneity or local outbreaks. By using multiple clusters we not only average over this variation, but we also get an estimate of the amount of variation between clusters, meaning we can account for it in our analysis.

Finally, we refer to "*pfhrp2/3*" deletions to capture the fact that researchers may be interested in either the *pfhrp2* or *pfhrp3* locus, but DRpower does not consider joint analysis of multiple loci and so we assume you are powering for just one set of deletion counts.

<p align="center">
<button class="btn btn-primary" onclick="window.location.href='https://mrc-ide.github.io/DRpower/articles/rationale2_issue.html';"> Next topic </button>
</p>
