# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_credible_prevalence_cpp <- function(args_params) {
    .Call(`_DRpower_get_credible_prevalence_cpp`, args_params)
}

get_credible_ICC_cpp <- function(args_params) {
    .Call(`_DRpower_get_credible_ICC_cpp`, args_params)
}

