# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

name: checks_develop

jobs:
  R-CMD-check:
    
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-20.04, r: 'release'}
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install Dependencies
        run: |
          Rscript -e "devtools::install_deps(dep = TRUE)"
      
      - name: Build Package
        run: |
          R CMD build . --no-build-vignettes
          
      - name: Check Package
        run: |
          R CMD check *tar.gz --ignore-vignettes

      - name: Run Tests
        run: |
          Rscript -e "devtools::test()"

